### PR TITLE
Feature/spring boot 3

### PR DESCRIPTION
**Pull request by michael-wirth**

### CODE REVIEW

**Comment by SilenceRainly** [comment]
Please agree to build workflow, I want to use the latest @michael-wirth

**Comment by michael-wirth** [comment]
@SilenceRainly 
I just created an update to ease the migration to Spring Boot 3 and made it available here.

This project is not maintained anymore.

The replacement in Spring Boot 3 is [Http Interface](https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#rest-http-interface).

**Comment by SilenceRainly** [comment]
But I am now relying on it a lot for my project and need new support for springboot3. @michael-wirth

**Comment by michael-wirth** [comment]
@SilenceRainly , not sure if this PR will be merged and made available. 

The best you can do is to build your own version depending on this PR.

**Comment by SilenceRainly** [comment]
Ok, Thanks.

**Comment by SilenceRainly** [comment]
Can you give me an example of spring cloud integrating http interface load balancing and fusion? I haven't found the relevant information yet! @michael-wirth

**Comment by michael-wirth** [comment]
@SilenceRainly 
The migration is not that difficult. I was using the WebClient implementation and had to update only the Annotations.
There is no Autoconfiguration to init the interfaces. You need to do it manually.


```kotlin
import org.springframework.context.annotation.Configuration
import org.springframework.web.service.annotation.GetExchange
import org.springframework.web.service.annotation.HttpExchange

@HttpExchange("http://myclient")
interface MyClient {
    @GetExchange("accounts")
    fun accounts(): Mono<AccountList>
}

@Configuration(proxyBeanMethods = false)
class MyClientConfiguration {

    @Bean
    fun myClient(myWebClientBuilder: WebClient.Builder) =
        HttpServiceProxyFactory.builder(WebClientAdapter.forClient(myWebClientBuilder.build())).build()
            .createClient(MyClient::class.java)
}
```

**Comment by SilenceRainly** [comment]
Is there any way to scan automatically? I didn't find it and forgot to inform you. Thank you. @michael-wirth

**Comment by michael-wirth** [comment]
@SilenceRainly , I'm not aware of any autoconfiguration. That's a question for the Spring Boot team. Of course, you can build your own scanner based on the [AbstractRetrofitClientsRegistrar](https://github.com/spring-projects-experimental/spring-cloud-square/blob/main/spring-cloud-square-retrofit-core/src/main/java/org/springframework/cloud/square/retrofit/core/AbstractRetrofitClientsRegistrar.java#L115)

**Comment by OlgaMaciaszek** [comment]
Hi @michael-wirth, thanks for submitting this PR. This project is still maintained in the experimental mode -at a slower pace- and we'll continue releasing it as necessary for as long as we maintain Spring Cloud `2021.x` release train (the next release is planned for later this month); we will provide some fixes and release a new version. However, we're not planning to make this project compatible with Spring Boot 3 or Spring Cloud 2022.x, since the suggested declarative clients solution starting with those release lines is[ Spring Interface Clients](https://docs.spring.io/spring-framework/docs/6.0.5-SNAPSHOT/reference/html/integration.html#rest-http-interface).

**Pull request closed without merging**
